collections:
  authors:
    output: true

# Defaults para layouts de todas as paginas
defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
